/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindMySolutionRouteImport } from './routes/find-my-solution'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMySolutionRoute = FindMySolutionRouteImport.update({
  id: '/find-my-solution',
  path: '/find-my-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/providers/': typeof ProvidersIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/providers': typeof ProvidersIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/providers/$id': typeof ProvidersIdRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/providers/': typeof ProvidersIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-my-solution'
    | '/providers'
    | '/solutions'
    | '/providers/$id'
    | '/solutions/$slug'
    | '/providers/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-my-solution'
    | '/providers/$id'
    | '/solutions/$slug'
    | '/providers'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/find-my-solution'
    | '/providers'
    | '/solutions'
    | '/providers/$id'
    | '/solutions/$slug'
    | '/providers/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindMySolutionRoute: typeof FindMySolutionRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-solution': {
      id: '/find-my-solution'
      path: '/find-my-solution'
      fullPath: '/find-my-solution'
      preLoaderRoute: typeof FindMySolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindMySolutionRoute: FindMySolutionRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
