/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as FindMySolutionRouteImport } from './routes/find-my-solution'
import { Route as JoinNetworkPartnerRouteImport } from './routes/join-network-partner'
import { Route as JoinProviderRouteImport } from './routes/join-provider'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as JoinUsIndexRouteImport } from './routes/join-us.index'
import { Route as JoinUsFinanceProviderRouteImport } from './routes/join-us.finance-provider'
import { Route as JoinUsNetworkPartnerRouteImport } from './routes/join-us.network-partner'
import { Route as JoinUsSolutionProviderRouteImport } from './routes/join-us.solution-provider'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesCategoryRouteImport } from './routes/resources.$category'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMySolutionRoute = FindMySolutionRouteImport.update({
  id: '/find-my-solution',
  path: '/find-my-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinNetworkPartnerRoute = JoinNetworkPartnerRouteImport.update({
  id: '/join-network-partner',
  path: '/join-network-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProviderRoute = JoinProviderRouteImport.update({
  id: '/join-provider',
  path: '/join-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinUsIndexRoute = JoinUsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinUsRoute,
} as any)
const JoinUsFinanceProviderRoute = JoinUsFinanceProviderRouteImport.update({
  id: '/finance-provider',
  path: '/finance-provider',
  getParentRoute: () => JoinUsRoute,
} as any)
const JoinUsNetworkPartnerRoute = JoinUsNetworkPartnerRouteImport.update({
  id: '/network-partner',
  path: '/network-partner',
  getParentRoute: () => JoinUsRoute,
} as any)
const JoinUsSolutionProviderRoute = JoinUsSolutionProviderRouteImport.update({
  id: '/solution-provider',
  path: '/solution-provider',
  getParentRoute: () => JoinUsRoute,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesCategoryRoute = ResourcesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ResourcesRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/drive': typeof DriveRoute
  '/events': typeof EventsRoute
  '/financing': typeof FinancingRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/join-network-partner': typeof JoinNetworkPartnerRoute
  '/join-provider': typeof JoinProviderRoute
  '/join-us': typeof JoinUsRouteWithChildren
  '/needs': typeof NeedsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/join-us/finance-provider': typeof JoinUsFinanceProviderRoute
  '/join-us/network-partner': typeof JoinUsNetworkPartnerRoute
  '/join-us/solution-provider': typeof JoinUsSolutionProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/join-us/': typeof JoinUsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/drive': typeof DriveRoute
  '/events': typeof EventsRoute
  '/financing': typeof FinancingRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/join-network-partner': typeof JoinNetworkPartnerRoute
  '/join-provider': typeof JoinProviderRoute
  '/needs': typeof NeedsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/join-us/finance-provider': typeof JoinUsFinanceProviderRoute
  '/join-us/network-partner': typeof JoinUsNetworkPartnerRoute
  '/join-us/solution-provider': typeof JoinUsSolutionProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/join-us': typeof JoinUsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/drive': typeof DriveRoute
  '/events': typeof EventsRoute
  '/financing': typeof FinancingRoute
  '/find-my-solution': typeof FindMySolutionRoute
  '/join-network-partner': typeof JoinNetworkPartnerRoute
  '/join-provider': typeof JoinProviderRoute
  '/join-us': typeof JoinUsRouteWithChildren
  '/needs': typeof NeedsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/stories': typeof StoriesRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/join-us/finance-provider': typeof JoinUsFinanceProviderRoute
  '/join-us/network-partner': typeof JoinUsNetworkPartnerRoute
  '/join-us/solution-provider': typeof JoinUsSolutionProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/resources/$category': typeof ResourcesCategoryRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/join-us/': typeof JoinUsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/drive'
    | '/events'
    | '/financing'
    | '/find-my-solution'
    | '/join-network-partner'
    | '/join-provider'
    | '/join-us'
    | '/needs'
    | '/opportunities'
    | '/providers'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/stories'
    | '/account'
    | '/admin'
    | '/join-us/finance-provider'
    | '/join-us/network-partner'
    | '/join-us/solution-provider'
    | '/providers/$id'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/stories/$slug'
    | '/join-us/'
    | '/providers/'
    | '/resources/'
    | '/solutions/'
    | '/stories/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/drive'
    | '/events'
    | '/financing'
    | '/find-my-solution'
    | '/join-network-partner'
    | '/join-provider'
    | '/needs'
    | '/opportunities'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/join-us/finance-provider'
    | '/join-us/network-partner'
    | '/join-us/solution-provider'
    | '/providers/$id'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/stories/$slug'
    | '/join-us'
    | '/providers'
    | '/resources'
    | '/solutions'
    | '/stories'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/drive'
    | '/events'
    | '/financing'
    | '/find-my-solution'
    | '/join-network-partner'
    | '/join-provider'
    | '/join-us'
    | '/needs'
    | '/opportunities'
    | '/providers'
    | '/resources'
    | '/sitemap.xml'
    | '/solutions'
    | '/stories'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/join-us/finance-provider'
    | '/join-us/network-partner'
    | '/join-us/solution-provider'
    | '/providers/$id'
    | '/resources/$category'
    | '/solutions/$slug'
    | '/stories/$slug'
    | '/join-us/'
    | '/providers/'
    | '/resources/'
    | '/solutions/'
    | '/stories/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  DriveRoute: typeof DriveRoute
  EventsRoute: typeof EventsRoute
  FinancingRoute: typeof FinancingRoute
  FindMySolutionRoute: typeof FindMySolutionRoute
  JoinNetworkPartnerRoute: typeof JoinNetworkPartnerRoute
  JoinProviderRoute: typeof JoinProviderRoute
  JoinUsRoute: typeof JoinUsRouteWithChildren
  NeedsRoute: typeof NeedsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  StoriesRoute: typeof StoriesRouteWithChildren
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-solution': {
      id: '/find-my-solution'
      path: '/find-my-solution'
      fullPath: '/find-my-solution'
      preLoaderRoute: typeof FindMySolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-network-partner': {
      id: '/join-network-partner'
      path: '/join-network-partner'
      fullPath: '/join-network-partner'
      preLoaderRoute: typeof JoinNetworkPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-provider': {
      id: '/join-provider'
      path: '/join-provider'
      fullPath: '/join-provider'
      preLoaderRoute: typeof JoinProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join-us/': {
      id: '/join-us/'
      path: '/'
      fullPath: '/join-us/'
      preLoaderRoute: typeof JoinUsIndexRouteImport
      parentRoute: typeof JoinUsRoute
    }
    '/join-us/finance-provider': {
      id: '/join-us/finance-provider'
      path: '/finance-provider'
      fullPath: '/join-us/finance-provider'
      preLoaderRoute: typeof JoinUsFinanceProviderRouteImport
      parentRoute: typeof JoinUsRoute
    }
    '/join-us/network-partner': {
      id: '/join-us/network-partner'
      path: '/network-partner'
      fullPath: '/join-us/network-partner'
      preLoaderRoute: typeof JoinUsNetworkPartnerRouteImport
      parentRoute: typeof JoinUsRoute
    }
    '/join-us/solution-provider': {
      id: '/join-us/solution-provider'
      path: '/solution-provider'
      fullPath: '/join-us/solution-provider'
      preLoaderRoute: typeof JoinUsSolutionProviderRouteImport
      parentRoute: typeof JoinUsRoute
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$category': {
      id: '/resources/$category'
      path: '/$category'
      fullPath: '/resources/$category'
      preLoaderRoute: typeof ResourcesCategoryRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JoinUsRouteChildren {
  JoinUsFinanceProviderRoute: typeof JoinUsFinanceProviderRoute
  JoinUsNetworkPartnerRoute: typeof JoinUsNetworkPartnerRoute
  JoinUsSolutionProviderRoute: typeof JoinUsSolutionProviderRoute
  JoinUsIndexRoute: typeof JoinUsIndexRoute
}

const JoinUsRouteChildren: JoinUsRouteChildren = {
  JoinUsFinanceProviderRoute: JoinUsFinanceProviderRoute,
  JoinUsNetworkPartnerRoute: JoinUsNetworkPartnerRoute,
  JoinUsSolutionProviderRoute: JoinUsSolutionProviderRoute,
  JoinUsIndexRoute: JoinUsIndexRoute,
}

const JoinUsRouteWithChildren =
  JoinUsRoute._addFileChildren(JoinUsRouteChildren)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesCategoryRoute: typeof ResourcesCategoryRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesCategoryRoute: ResourcesCategoryRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  DriveRoute: DriveRoute,
  EventsRoute: EventsRoute,
  FinancingRoute: FinancingRoute,
  FindMySolutionRoute: FindMySolutionRoute,
  JoinNetworkPartnerRoute: JoinNetworkPartnerRoute,
  JoinProviderRoute: JoinProviderRoute,
  JoinUsRoute: JoinUsRouteWithChildren,
  NeedsRoute: NeedsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  StoriesRoute: StoriesRouteWithChildren,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
